# Project: Zumbi
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../Chefe.o ../Data.o ../main.o ../Mapa.o ../Zumbi.o ../Humano.o ../ZumbiHunter.o
LINKOBJ  = ../Chefe.o ../Data.o ../main.o ../Mapa.o ../Zumbi.o ../Humano.o ../ZumbiHunter.o
LIBS     = -L"C:/Dev-Cpp/MinGW64/lib" -L"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++" -I"C:/Boost"
BIN      = Zumbi.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c++11
CFLAGS   = $(INCS) -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../Chefe.o: ../Chefe.cpp
	$(CPP) -c ../Chefe.cpp -o ../Chefe.o $(CXXFLAGS)

../Data.o: ../Data.cpp
	$(CPP) -c ../Data.cpp -o ../Data.o $(CXXFLAGS)

../main.o: ../main.cpp
	$(CPP) -c ../main.cpp -o ../main.o $(CXXFLAGS)

../Mapa.o: ../Mapa.cpp
	$(CPP) -c ../Mapa.cpp -o ../Mapa.o $(CXXFLAGS)

../Zumbi.o: ../Zumbi.cpp
	$(CPP) -c ../Zumbi.cpp -o ../Zumbi.o $(CXXFLAGS)

../Humano.o: ../Humano.cpp
	$(CPP) -c ../Humano.cpp -o ../Humano.o $(CXXFLAGS)

../ZumbiHunter.o: ../ZumbiHunter.cpp
	$(CPP) -c ../ZumbiHunter.cpp -o ../ZumbiHunter.o $(CXXFLAGS)
